# Generated by Django 5.0.2 on 2024-11-28 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_price', models.IntegerField(null=True)),
                ('product_status', models.BooleanField(default=False, null=True)),
                ('product_datestamp', models.DateTimeField(default=datetime.datetime(2024, 11, 28, 20, 48, 16, 725414), null=True)),
            ],
        ),
    ]
